version: "3"
services:
  app:
    image: node:latest
    container_name: app
    entrypoint: /bin/sh
    ports:
      - 5173:5173
    working_dir: /var/www/app
    volumes:
      - type: bind
        source: .
        target: /var/www/app
    tty: true
